server:
  port: 8081

spring:
  application:
    name: hotel-chat
  zipkin:
    base-url: http://localhost:9411
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    