spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes: 
        - id: hotel
          uri: lb://HOTEL
          predicates:
            - Path=/api/v1/hotels/**        
        - id: menu
          uri: lb://MENU
          predicates:
            - Path=/api/v1/menus/**
server:
  port: 8083
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true