apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-menu
  labels:
    app: hotel-menu
spec:
  replicas: 1 #achtung
  template:
    metadata:
      name: hotel-menu
      labels:
        app: hotel-menu
    spec:
      containers:
        - name: hotel-menu
          image: getsoftware-eu/hotel-menu:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube #//application-kube.properties will be seleced
      restartPolicy: Always
  selector:
    matchLabels:
      app: hotel-menu
