apiVersion: v1
kind: Service
metadata:
  name: hotel-notification-service
spec:
  selector:
    app: notification
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer #Eugen: LoadBalancer for our POD